services:
  mysql:
    image: mysql:8.0
    container_name: mysql_vuln_fix
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD : ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: api_vuln_fix
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_HOST: mysql
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
